// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type Page = Collections['Page']['schema']['_output']
export declare const Page: Page[]
