name: docker(multi stage)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  TAG: ${{ github.run_number }}
  TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  REGISTRY: ghcr.io
  DOCKERFILE: multi.dockerfile
  IMAGE_NAME: koenverburg/template-nextjs/nextjs-multi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: ${{ env.TAG }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ env.DOCKERFILE }}
          context: .
          platforms: linux/arm/v7, linux/amd64
          # platforms: linux/arm/v7, linux/arm64,linux/amd86
          tags: ${{ steps.meta.outputs.tags }}
