name: docker(standalone)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  TAG: ${{ github.run_number }}
  TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  REGISTRY: ghcr.io
  DOCKERFILE: standalone.dockerfile
  IMAGE_NAME: koenverburg/template-nextjs/nextjs-standalone

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: ${{ env.TAG }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ env.DOCKERFILE }}
          context: .
          platforms: linux/amd64
          # platforms: linux/arm/v7, linux/arm64,linux/amd86
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Environment Variables
        uses: danielr1996/envsubst-action@1.0.0
        env:
          TAG: ${{ env.TAG }}
        with:
          input: k8s/temp-deployment.yaml
          output: deployment.yaml

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: koenverburg

      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: koenverburg
          manifest: deployment.yaml
          # tag: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          waitOn: deployment/nextjs

      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://nextjs-koenverburg.cloud.okteto.net"
          expected-statuses: "200"
