name: static build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: pnpm build

      - run: pnpm export

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build-output
          path: ./dist
          retention-days: 2

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download nextjs output
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build-output
          path: ./dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          # cname: <your domain>
          github_token: ${{ secrets.GITHUB_TOKEN }}
